### ISSUE TITLE
Widget which shows all thick jobs is required

### ISSUE THREAD

**Issue by maksimsarychau** [qaprosoft/zafira#1745] opened 2019-08-29 20:59 UTC
I have to find all suites\jobs which are the most slowest\quickest and work with them. 
Project, execution time,  order fields should we configurable. 
Good to have suite name with the link, pass rate and exact execution time in results. 

Also, it will be useful to have such filter on Run view for a limited time period (nightly, weekly, etc)

**Comment by vdelendik** [comment] 2019-09-09 17:10
@maksimsarychau 
as of now you can use regular nightly/env regression widget with failures subject: aborted by timeout".

extra performance widget templates could be generated later. requirements - TBD.

**Comment by nsidorevich** [comment] 2019-11-14 13:25
Marking as "help wanted" because of @vdelendik 's comment that exact requirements for performance widget templates will be detailed later. Until then labeled accordingly.

**Comment by nsidorevich** [comment] 2019-11-15 14:50
Test run search by "aborted" status should be used in order to achieve this.

**Closed by nsidorevich** 2019-11-15 14:50 UTC
Labels: enhancement, wontfix
