### ISSUE TITLE
Test results transfer to TestRail with wrong test case Ids when using data provider

### ISSUE THREAD

**Issue by deNatallia** [qaprosoft/zafira#1405] opened 2019-03-20 15:09 UTC
As the result of using data provider for a group of test cases with different Test case ids, the result (and logs/link to Zafira test run) of the first test is set as result of the second one in Test Rail and so on. 

in Zafira:                                                    
test1 - passed                                
test2 - failed                                  
test3 - passed                               

in Test Rail:
test1 - failed
test2 - passed
test3 - status of test that run after it

**Comment by vdelendik** [comment] 2019-03-20 16:03
the root cause is that:
1) we do getTestTags in ZafiraListener onTestStart
2) during the test execution we allow to update cases using
setCases(String..id)
3) overridden cases are stored in threadLocal variable and are registered for the next test run
-> so in reality we have shift in cases registration when 'setCases...' is used on test level

**Comment by kmehta30** [comment] 2019-04-02 06:03
Hi deNatallia,

I am also facing the same issue that with data provider test cases how the test rail api's upadate the same test case.

**Comment by vdelendik** [comment] 2019-05-19 11:32
@deNatallia @kmehta30 issue is fixed in carina and zafira:
carina - [6.1.20+](https://github.com/qaprosoft/carina/releases/tag/6.1.20)
zafira - 4.0.53

**Closed by vdelendik** 2019-05-19 11:32 UTC
Labels: bug
